services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env.database
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env.database
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - api-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - "5672:5672"     
      - "15672:15672"   
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - api-network

volumes:
  pgdata:
  rabbitmq_data:

networks:
  api-network:
    driver: bridge